//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePartsServices_CodingTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOptionsTable
    {
        public int Option_Number { get; set; }
        public string Option_Text { get; set; }
        public int ProductOption_ID { get; set; }
    
        public virtual ProductTable Product_ID { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
