//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePartsServices_CodingTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTable()
        {
            this.ProductOptionsTables = new HashSet<ProductOptionsTable>();
        }
    
        public int Product_ID { get; set; }
        public bool Product_Active { get; set; }
        public string Product_Number_Custom { get; set; }
        public decimal Cost_Price { get; set; }
        public string Product_Description { get; set; }
    
        public virtual ManufacturerTable Manufacturer_ID { get; set; }
        public virtual ManufacturerTable ManufacturerTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOptionsTable> ProductOptionsTables { get; set; }
    }
}
